[package]
name = "scorepeek"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[package.metadata.dist]
dist = true

[dependencies]
scorepeek-overlay = { path = "../scorepeek-overlay" }
scorepeek-scores = { path = "../scorepeek-scores" }
encoding_rs.workspace = true
imageproc.workspace = true
ort.workspace = true
pipewire.workspace = true
qoi.workspace = true
ratatui.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
signal-hook.workspace = true
tempfile.workspace = true
unicode-normalization.workspace = true
ureq.workspace = true
uuid.workspace = true
x11rb.workspace = true

[lints]
workspace = true

[features]
embedded-web = ["scorepeek-overlay/embedded-web"]
