[package]
name = "scorepeek-skin-cyan-system"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
scorepeek-skin-shared = { path = "../shared" }

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = "deny"
pedantic = "deny"
