//! Offline outline export using skrifa already pinned in this workspace's lockfile.
use skrifa::{
    FontRef, MetadataProvider,
    instance::{LocationRef, Size},
    outline::{DrawSettings, OutlinePen},
};
use std::{fmt::Write, fs};
#[derive(Default)]
struct Path(String);
impl OutlinePen for Path {
    fn move_to(&mut self, x: f32, y: f32) {
        write!(self.0, "M{x:.2},{:.2}", 60.0 - y).unwrap();
    }
    fn line_to(&mut self, x: f32, y: f32) {
        write!(self.0, "L{x:.2},{:.2}", 60.0 - y).unwrap();
    }
    fn quad_to(&mut self, cx: f32, cy: f32, x: f32, y: f32) {
        write!(self.0, "Q{cx:.2},{:.2} {x:.2},{:.2}", 60.0 - cy, 60.0 - y).unwrap();
    }
    fn curve_to(&mut self, cx: f32, cy: f32, dx: f32, dy: f32, x: f32, y: f32) {
        write!(
            self.0,
            "C{cx:.2},{:.2} {dx:.2},{:.2} {x:.2},{:.2}",
            60.0 - cy,
            60.0 - dy,
            60.0 - y
        )
        .unwrap();
    }
    fn close(&mut self) {
        self.0.push('Z');
    }
}
fn main() {
    let bytes = fs::read("skins/infinitas/resources/ChakraPetch-SemiBoldItalic.ttf").unwrap();
    let font = FontRef::new(&bytes).unwrap();
    let outlines = font.outline_glyphs();
    let metrics = font.glyph_metrics(Size::new(80.0), LocationRef::default());
    let chars = " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+-/%.:?";
    let mut result = String::from(
        "// Generated by tools/outline.rs; pinned Chakra Petch, 80 px outlines.\npub const GLYPHS: &[(f64, &str)] = &[\n",
    );
    for c in chars.chars() {
        let id = font.charmap().map(c).unwrap();
        let mut path = Path::default();
        if let Some(g) = outlines.get(id) {
            g.draw(
                DrawSettings::unhinted(Size::new(80.0), LocationRef::default()),
                &mut path,
            )
            .unwrap();
        }
        writeln!(
            result,
            "({:.4}, {:?}),",
            metrics.advance_width(id).unwrap(),
            path.0
        )
        .unwrap();
    }
    result.push_str("];\n");
    fs::write("skins/infinitas/src/glyphs.rs", result).unwrap();
}
